### ISSUE TITLE
Enchancement: Sort output by player by player name

### ISSUE THREAD

**Issue by dozens** [damanar/platy#2]
Sort the output by player name so it will be easier for each individual to find their responsibilities.

Now:
Pandatron :: territory 1 - platoon 5 :: Cassian Andor
Delmon Ciiid'r :: territory 1 - platoon 2 :: K-2SO
J'Attic :: territory 1 - platoon 1 :: Chirrut Îmwe
...
...

Change to:
Delmon Ciiid'r :: territory 1 - platoon 2 :: K-2SO
J'Attic :: territory 1 - platoon 1 :: Chirrut Îmwe
Pandatron :: territory 1 - platoon 5 :: Cassian Andor

**Comment by damanar** [comment]
added sorting by player name
